In [2]:
import numpy as np


In [4]:
My_Arr = np.array([[1,2],[8,9]])

In [5]:
My_Arr


array([[1, 2],
       [8, 9]])

In [6]:
My_Matrix = np.matrix([[1,2],[8,9]])

In [7]:
My_Matrix


matrix([[1, 2],
        [8, 9]])

In [10]:
My_3D_Arr = np.array([[1,2,10],[3,4,11],[7,8,12]])

In [15]:
Result = My_3D_Arr @ My_3D_Arr
Result


array([[ 77,  90, 152],
       [ 92, 110, 206],
       [115, 142, 302]])

Multiply arrays 

In [16]:
Result2 = np.dot(My_3D_Arr , My_3D_Arr)
Result2

array([[ 77,  90, 152],
       [ 92, 110, 206],
       [115, 142, 302]])

Multiply arrays 

In [21]:
np.multiply(My_3D_Arr , My_3D_Arr)

array([[  1,   4, 100],
       [  9,  16, 121],
       [ 49,  64, 144]])

Multiply each value by its corresponding value 

In [19]:
np.prod(My_3D_Arr) 

1774080

* multiply of all members 

In [30]:
My_Result3 = np.array([1,2,3])
My_Result3 = My_Result3 + 5
My_Result3 


array([6, 7, 8])

* Broadcasting

In [27]:
c = np.ones((3,3))

In [28]:
c


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
c + My_Result3

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

* Broadcasting

In [31]:
c = np.ones((3,1))
c

array([[1.],
       [1.],
       [1.]])

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
b = np.array([3,4,5])
b


array([3, 4, 5])

In [36]:
c + b

array([[4., 5., 6.],
       [4., 5., 6.],
       [4., 5., 6.]])

* Broadcasting

In [40]:
np.sum(My_Result3)


21

Sum of all members

In [43]:
c + b

array([[4., 5., 6.],
       [4., 5., 6.],
       [4., 5., 6.]])

In [41]:
np.sum(c + b)

45.0

In [42]:
np.cumsum(c + b)

array([ 4.,  9., 15., 19., 24., 30., 34., 39., 45.])

 Sum of each element with the sum of the elements before it 

In [44]:
np.cumsum((c + b) , axis = 0)

array([[ 4.,  5.,  6.],
       [ 8., 10., 12.],
       [12., 15., 18.]])

In [45]:
np.cumsum((c + b) , axis = 1)

array([[ 4.,  9., 15.],
       [ 4.,  9., 15.],
       [ 4.,  9., 15.]])

In [46]:
np.subtract((c + b) , b)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.divide([8 , 4 , 3.24] , 2)

array([4.  , 2.  , 1.62])

In [49]:
np.floor_divide([8 , 4 , 3.24] , 2)

array([4., 2., 1.])

In [50]:
np.math.sqrt(16)

4.0

In [52]:
np.math.nan

nan

nan = not a number

In [53]:
np.math.inf

inf

inf = infinity

In [54]:
np.random.uniform(1 , 5 , (2,3))

array([[4.3488942 , 3.1839082 , 2.86050305],
       [2.64080356, 1.58267021, 3.89996212]])

Random Numbers Between 1 and 5

In [57]:
np.random.standard_normal((3,1))

array([[-0.36142707],
       [-2.50620361],
       [-0.26304175]])

In [58]:
np.arange(1, 10, 3)

array([1, 4, 7])

Creat a sequence of numbers from 1 to 10 with step size = 3

In [59]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [60]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

Take 3 numbers from 1 to 10 

In [6]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [7]:
np.size(a)

4

In [8]:
np.shape(a)

(2, 2)

In [9]:
First_Arr = ([1,2,5,6,1,8,7,4,3,3,2])
Second_Arr = ([9,2,2,2,7,5,3,11,1])


In [10]:
np.unique(First_Arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
np.union1d(First_Arr , Second_Arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11])

In [12]:
np.intersect1d(First_Arr , Second_Arr)

array([1, 2, 3, 5, 7])

In [13]:
np.mean(First_Arr )

3.8181818181818183

In [14]:
np.mean(Second_Arr)

4.666666666666667

In [15]:
np.median(First_Arr)

3.0

In [16]:
np.std(First_Arr)

2.289032420366213

std = standard deviation

In [17]:
np.var(First_Arr)

5.239669421487604

var = variance

In [18]:
Polynomials = np.array([1,3,3])
np.polyval(Polynomials , 4)

31

x^2 + 3x + 3 with x=4

In [19]:
np.polyder(Polynomials)

array([2, 3])

Derivative 

In [20]:
np.polyint(Polynomials)

array([0.33333333, 1.5       , 3.        , 0.        ])

 Integral = x^3/3 + 1.5x^2 + 3x 